-- ============================================================
-- NEPA Conclave 2026 — Party allocation list refresh
-- Source: DELIGATES LIST - Copy.xlsx  (generated 2026-09-19)
-- 257 parties. Run in Supabase -> SQL Editor. Safe & idempotent.
-- SELF-GUARDING: aborts if any registration is already linked to a
-- party (i.e. help-desk registration has started), so it can never
-- orphan live delegates. In that case use a name-merge instead.
-- ============================================================
begin;

do $$ begin
  if exists (select 1 from registrations where party_id is not null and archived_at is null) then
    raise exception 'ABORT: registrations are already linked to parties. Do NOT run the destructive refresh; use a name-merge to preserve links.';
  end if;
end $$;

delete from parties;

insert into parties (name, category, paid_count, amount, notes, original_paid, sort, active) values
  ('A K BANIK, COOCHBIHAR', 'full', 1, null, null, '1', 0, true),
  ('A K ENGINEERING', 'full', 1, null, null, '1', 1, true),
  ('AGRA- B P OIL MILLS PVT LTD (ELEPHANT BRAND)', 'full', 1, null, null, '1', 2, true),
  ('AGRA- MAHESH EDIBLE OIL INDS LTD (SALONI)', 'full', 4, null, null, '4', 3, true),
  ('AGRA OIL INDUSTRIES (KUMAR BABU) AGRA', 'full', 5, null, null, '5', 4, true),
  ('AGRA-B K CASTING AGRA (ANURAG BANSAL + KHALID AHMAD)', 'full', 1, null, null, '1', 5, true),
  ('AHMEDABAD- GOKUL AGRO RESOURSES LTD (VTL)', 'full', 2, null, null, '2', 6, true),
  ('AHMEDABAD- OZONE : SAMIRKUMAR DASRATHMAL PATEL', 'full', null, null, null, null, 7, true),
  ('AHMEDABAD- OZONE PROCON PRIVATE LIMITED', 'full', 5, null, null, '5', 8, true),
  ('AIZAWL- MOSIA AGENCIES', 'full', 1, null, null, '1', 9, true),
  ('AJMER TRADE AGENCY : 03.09.26 EDC', 'full', 1, null, null, '1', 10, true),
  ('ALWAR- RITIKA VEG OILS PVT LTD/ BABULA EDI', 'full', 8, null, null, '8', 11, true),
  ('ATITHI AGRO PRODUCTS LLP', 'full', 2, null, null, '2', 12, true),
  ('B D EDIBLE OIL PVT LTD', 'full', 1, null, null, '1', 13, true),
  ('B M OILS PVT LIMITED  || GST', 'full', 1, null, null, '1', 14, true),
  ('BARPETA- ANURAG Agencies', 'full', 1, null, null, '1', 15, true),
  ('BELAGAVI- CREATIVE ENGINEERS AND CONSULTANT', 'full', 4, null, null, '4', 16, true),
  ('BHABANI INDUSTRIES : BHAVIK AGARWAL 11.09.26 EDC', 'full', 1, null, null, '1', 17, true),
  ('BHARAT AGRO OIL PVT LTD, MODINAGAR', 'full', 2, null, null, '2', 18, true),
  ('BHARAT OIL INDUSTRIES', 'full', 2, null, null, '2', 19, true),
  ('BHARATPUR- B R OIL MILLS (RANI BRAND),', 'full', 16, null, null, '16', 20, true),
  ('BHARATPUR- MANGLAM PACKEGING INDUSTRIES', 'full', 1, null, null, '1', 21, true),
  ('BHARATPUR- SHREE SHANTI OIL MILL', 'full', 1, null, null, '1', 22, true),
  ('BHIWANI- MUNGIPA AGRO PRODUCTS', 'full', null, null, null, null, 23, true),
  ('BHUSHAN OIL FATS PVT LTD : SHAHI BHUSHAN', 'full', 1, null, null, '1', 24, true),
  ('BIKANER- AJITNATH INDUSTRIES', 'full', 3, null, null, '3', 25, true),
  ('BUDGE BUDGE REFINERIES LTD', 'full', 2, null, null, '2', 26, true),
  ('DELHI- BABAJI UDYOG PRIVATE LTD', 'full', 1, null, null, '1', 27, true),
  ('DEVENDRA TRADING CO: KISHOR GARG MORENA:', 'full', 1, null, null, '1', 28, true),
  ('DHEKIAJULI- MAHABIR PD MAHENDER KUMAR', 'full', 1, null, null, '1', 29, true),
  ('DHOLPUR- SHRI RADHARANI EDIBLE OILS PVT LTD', 'full', 3, null, null, '3', 30, true),
  ('DHUBRI- HARLALKA MANUFACTURING ENTERPRISES', 'full', 1, null, null, '1', 31, true),
  ('DIBRUGARH- Mahabir Prasad Tilok Chand', 'full', 1, null, null, '1', 32, true),
  ('DIBRUGARH- PATNI AND SONS', 'full', 1, null, null, '1', 33, true),
  ('DIBRUGARH- Shree Niwas Basudeo & Co', 'full', 1, null, null, '1', 34, true),
  ('DIBRUGARH- SOHANLAL CHUNNI LAL', 'full', 1, null, null, '1', 35, true),
  ('DIMAPUR- NOBLE TRADING', 'full', 1, null, null, '1', 36, true),
  ('DIMAPUR- North East Marketting Co', 'full', 1, null, null, '1', 37, true),
  ('DIMAPUR- PULOTO ENTERPRISES', 'full', 1, null, null, '1', 38, true),
  ('DINAJPUR- KALYANI SOLVEX PVT LTD', 'full', 2, null, null, '2', 39, true),
  ('DVC PROCESS TECHNOLOGIES INDIA PVT LTD, PUNE', 'full', 2, null, null, '2', 40, true),
  ('EMAMI AGROTECH LTD          || GST', 'full', 5, null, null, '5', 41, true),
  ('G TECH PACKING INDIA PVT LTD', 'full', 2, null, null, '2', 42, true),
  ('GANPATGANJ- RAJ KUMAR AGRAWAL', 'full', 1, null, null, '1', 43, true),
  ('GANPATIGUNJ- RAJ KUMAR AGARWAL', 'full', null, null, null, null, 44, true),
  ('GHY- Ajit sing bothra & sons', 'full', 1, null, null, '1', 45, true),
  ('GHY- Akshay jain broker', 'full', 1, null, null, '1', 46, true),
  ('GHY- AYUSH BHARTIA', 'full', 1, null, null, '1', 47, true),
  ('GHY- BANAR DARBAR BHANDAR,', 'full', 1, null, null, '1', 48, true),
  ('GHY- CENTURY MERCANTILE PVT LTD', 'full', 2, null, null, '2', 49, true),
  ('GHY- CHAUDHARY TRADE AND AGENCY', 'full', 1, null, null, '1', 50, true),
  ('GHY- GANGH AND SONS', 'full', 1, null, null, '1', 51, true),
  ('GHY- HOMTEK INDIA SNACKS MFG CO', 'full', 1, null, null, '1', 52, true),
  ('GHY- J S ENTERPRISES, SETHIAJI', 'full', 1, null, null, '1', 53, true),
  ('GHY- J S ENT (SETHIAJI) A/C SWASTIK', 'full', 2, null, null, '2', 54, true),
  ('GHY- JAIN GRAIN', 'full', 1, null, null, '1', 55, true),
  ('GHY- KAMAKHYA AGRO IMPEX INDIA AND CO', 'full', 1, null, null, '1', 56, true),
  ('GHY- KAPIL JHA', 'full', 1, null, null, '1', 57, true),
  ('GHY- MANDAL & BROTHERS', 'full', 1, null, null, '1', 58, true),
  ('GHY- MOTHER DAIRY:DHARA MAHESH SHAH', 'full', 5, null, null, '5', 59, true),
  ('GHY- MOUR ENTERPRISE', 'full', 0, null, null, '0', 60, true),
  ('GHY- NAVYA OILS', 'full', 1, null, null, '1', 61, true),
  ('GHY- NIRU JAIN', 'full', 1, null, null, '1', 62, true),
  ('GHY- PRAGYAY', 'full', 1, null, null, '1', 63, true),
  ('GHY- R B SURANA AND SONS', 'full', 1, null, null, '1', 64, true),
  ('GHY- R K FOOD INDUSTRIES, (ARYAN)', 'full', 2, null, null, '2', 65, true),
  ('GHY- R S ENTERPRISES,', 'full', 1, null, null, '1', 66, true),
  ('GHY- S SOMANI AND SONS', 'full', 1, null, null, '1', 67, true),
  ('GHY- SACCHASHIV TRADING HOUSE', 'full', 1, null, null, '1', 68, true),
  ('GHY- Somani Enterprises', 'full', 1, null, null, '1', 69, true),
  ('GHY- SREENIWAS BASUDEO DEORAH AND CO', 'full', 1, null, null, '1', 70, true),
  ('GHY- TRILOK ENTERPRISE', 'full', 1, null, null, '1', 71, true),
  ('GHY- UNIVERSAL TRADE AGENCY', 'full', 3, null, null, '3', 72, true),
  ('GOALPARA- NATURAL FOOD PRODUCTS,', 'full', 1, null, null, '1', 73, true),
  ('GOEL UDYOG AGENCY: 11.09.26 EDC', 'full', 1, null, null, '1', 74, true),
  ('GORAKHPUR- GRL EDIBLES PRIVATE LIMITED', 'full', 1, null, null, '1', 75, true),
  ('GUJRAT- NETAJI OIL DEPOT PRIVATE LIMITED', 'full', 1, null, null, '1', 76, true),
  ('GURUGRAM- K.S. OILS LIMITED,', 'full', 5, null, null, '5', 77, true),
  ('HAILAKANDI- Dey Commercial', 'full', 1, null, null, '1', 78, true),
  ('HALDAR VENTURES LTD || ALLOCATION', 'full', 4, null, null, '4', 79, true),
  ('HARI OIL & GENERAL MILL S   (ENGINE)  (HOM) BHTR', 'full', 8, null, null, '8', 80, true),
  ('HARI SHANKER AND CO', 'full', 1, null, null, '1', 81, true),
  ('HARI VEGITABLE PROD PVT LTD (ENGINE) (HVPPL)', 'full', 12, null, null, '12', 82, true),
  ('HARYANA- LOIOS DREYFUS  RAJESH K PRADHAN 15.09.26 EDC', 'full', 1, null, null, '1', 83, true),
  ('HISSAR- MUKESH GINNING MILLS', 'full', 1, null, null, '1', 84, true),
  ('HOMTEK INDIA PVT LTD', 'full', 2, null, null, '2', 85, true),
  ('HYDRO PRESS INDUSTRIES, (BRONZ)', 'full', 2, null, null, '2', 86, true),
  ('IMPHAL- Ajay Traders', 'full', 1, null, null, '1', 87, true),
  ('IMPHAL- MODERN STORE', 'full', 1, null, null, '1', 88, true),
  ('JAIPUR- BHARDWAJ OIL INDS (MAHESH JAIN NEWAI)', 'full', 2, null, null, '2', 89, true),
  ('JAIPUR- MARUDHAR TRADING AGENCY', 'full', 1, null, null, '1', 90, true),
  ('JAIPUR- S R OIL MILLS', 'full', 1, null, null, '1', 91, true),
  ('JAIPUR- SHIVAM FOOD PRODUCTS, ANKIT', 'full', null, null, null, null, 92, true),
  ('JAIPUR- SHRI HARI OIL TRADERS ,', 'full', 1, null, null, '1', 93, true),
  ('JAIPUR- SVR AGROTECH PVT LIMITED', 'full', 1, null, null, '1', 94, true),
  ('JAIPUR- TIRUPATI UDYOG', 'full', 2, null, null, '2', 95, true),
  ('JAIPUR- V.K.SHARMA & CO.', 'full', 1, null, null, '1', 96, true),
  ('JAIPUR- VIDHYA SAGAR PROTIENS PVT LTD', 'full', 1, null, null, '1', 97, true),
  ('JAIPUR-BHAWANI SILICATE INDUSTRIES', 'full', 1, null, null, '1', 98, true),
  ('JAISWAL ALLIENCE :12.09.26 EDC', 'full', 1, null, null, '1', 99, true),
  ('JHARKHAND- GOYAL TRADING COMPANY', 'full', 1, null, null, '1', 100, true),
  ('JOGBANI- RAJDHANI TRANSPORT CARGO |', 'full', 2, null, null, '2', 101, true),
  ('JONU GUPTA/PUNIT GOYAL   EDC 02.09.26', 'full', 2, null, null, '2', 102, true),
  ('JORHAT- EVEREST AGENCY HOUSE', 'full', 1, null, null, '1', 103, true),
  ('JORHAT- G S OIL & FOODS', 'full', 1, null, null, '1', 104, true),
  ('JORHAT- JAYSHREE RAJASTHAN STORE', 'full', 1, null, null, '1', 105, true),
  ('JORHAT- KRISHNA TRADING COMPANY', 'full', 1, null, null, '1', 106, true),
  ('JORHAT- MODI ENTERPRISE', 'full', 1, null, null, '1', 107, true),
  ('JORHAT- PURUSOTAM P JOSHI 16.09.26 EDC', 'full', 1, null, null, '1', 108, true),
  ('JORHAT- Radhe Shyam Ram Vilas', 'full', 1, null, null, '1', 109, true),
  ('JORHAT- RATHI TRADERS', 'full', 1, null, null, '1', 110, true),
  ('JORHAT- SITARAM RAMESHWAR LAL', 'full', 1, null, null, '1', 111, true),
  ('JORHAT- TOLARAM SURENDER KR KUNDALIA', 'full', 1, null, null, '1', 112, true),
  ('JORHAT- VISHAL ENTERPRISES', 'full', 1, null, null, '1', 113, true),
  ('K B SAHA INDUSTRIES PVT LTD', 'full', null, null, null, null, 114, true),
  ('Kalyan Trading co,', 'full', 1, null, null, '1', 115, true),
  ('KANPUR- KANPUR EDIBLES PVT LTD (SUNIL Gupta),', 'full', 5, null, null, '5', 116, true),
  ('KANPUR- MANTORA OIL PRODUCTS PRIVATE LIMITED', 'full', 4, null, null, '4', 117, true),
  ('KANPUR- VAIBHAV EDIBLES PVT LIMITED', 'full', 2, null, null, '2', 118, true),
  ('KARIMGUNJ- ARIHANT  AND CO', 'full', 1, null, null, '1', 119, true),
  ('KARIMGUNJ- HINDUSTAN TRADIN KMJ', 'full', 1, null, null, '1', 120, true),
  ('KARIMGUNJ- KARIMGUNJ SARAOGI TRADING CO,', 'full', 2, null, null, '2', 121, true),
  ('KARIMGUNJ- LALCHAND CHAGAN MAL', 'full', 2, null, null, '2', 122, true),
  ('KARIMGUNJ- MOHID TRADERS', 'full', 1, null, null, '1', 123, true),
  ('KARIMGUNJ- SAHIRAM BAJRANG LAL', 'full', 1, null, null, '1', 124, true),
  ('KARIMGUNJ- SHREE JAIN TRADERS', 'full', 1, null, null, '1', 125, true),
  ('KARIMGUNJ- SINGH BROTHERS', 'full', 1, null, null, '1', 126, true),
  ('Khandelia Oil and General Mills P Ltd (NEPA26-1031)', 'full', 1, null, null, '1', 127, true),
  ('KHARUPETIA- RAHUL SAHA 16.09.26 EDC', 'full', 1, null, null, '1', 128, true),
  ('KHARUPETIA- SHREE HANUMAN OIL INDUSTRIES', 'full', 1, null, null, '1', 129, true),
  ('KOLKATA-  ASHIAN OILS PRIVATE LIMITED', 'full', 6, null, null, '6', 130, true),
  ('KOLKATA- A B UDYOG PVT LTD', 'full', 2, null, null, '2', 131, true),
  ('KOLKATA- BISHAMBHAR DAYAL RAMSWARUP', 'full', 1, null, null, '1', 132, true),
  ('KOLKATA- DEENDAYAL SHARWAN KUMAR', 'full', 1, null, null, '1', 133, true),
  ('KOLKATA- MODI OIL  PACKAGERS PVT LTD', 'full', 1, null, null, '1', 134, true),
  ('KOLKATA- MODI OIL PACKAGERS PVT LTD : VEENIT MODI', 'full', null, null, null, null, 135, true),
  ('KOLKATA- PANCHAM MERCHANTIS', 'full', 6, null, null, '6', 136, true),
  ('KOLKATA- RAJA ENTERPRISES., VIKASH AGARWAL', 'full', 1, null, null, '1', 137, true),
  ('KOLKATA- RAJESH KHAITAN', 'full', 1, null, null, '1', 138, true),
  ('KOLKATA- RANISATI AGRO OILS PVT LTD', 'full', 1, null, null, '1', 139, true),
  ('KOLKATA- RATAN LAL RAVINDRA KUMAR', 'full', 2, null, null, '2', 140, true),
  ('KOLKATA- TRINITY FINANCE AND CREDIT PVT LTD', 'full', 1, null, null, '1', 141, true),
  ('KOTA- GOYAL VEGOILS LTD(PANKAJ & DINESH JI)', 'full', 4, null, null, '4', 142, true),
  ('LAHARIA OIL INDS P LTD', 'full', 2, null, null, '2', 143, true),
  ('LALABAZAR- RUPAN MODAK', 'full', 2, null, null, '2', 144, true),
  ('LALABAZAR- SUBIR MODAK', 'full', 1, null, null, '1', 145, true),
  ('MAA PET & CLOSURES', 'full', 1, null, null, '1', 146, true),
  ('MANIK CHAND SONI :EDC 06.09.26', 'full', 1, null, null, '1', 147, true),
  ('MANIPUR- K P ENTERPRISES,', 'full', 1, null, null, '1', 148, true),
  ('MEERUT- AGARWAL EDIBLES', 'full', 1, null, null, '1', 149, true),
  ('MORAN- BB AND SONS', 'full', 1, null, null, '1', 150, true),
  ('MORENA- B R OIL INDUSTRIES PVT LTD', 'full', 8, null, null, '8', 151, true),
  ('MORENA- KBL AGRO PVT LTD (MOJ BRAND)', 'full', 2, null, null, '2', 152, true),
  ('MUMBAI- MUEZ HEST INDIA PVT LTD', 'full', 2, null, null, '2', 153, true),
  ('N R TRADING COMPANY        || GST', 'full', 1, null, null, '1', 154, true),
  ('NAGAON- MADHAV INDUSTRIES', 'full', 1, null, null, '1', 155, true),
  ('NAGAON- PAWAN INDUSTRIES', 'full', 1, null, null, '1', 156, true),
  ('NAGPAL AND SONS               ||  GST', 'full', 2, null, null, '2', 157, true),
  ('NATIONAL AGRO FOODS /DEEPAK+VATSAL', 'full', 2, null, null, '2', 158, true),
  ('NEHA INDUSTRIES, ALWAR', 'full', 1, null, null, '1', 159, true),
  ('NIRANJAN LAL', 'full', 1, null, null, '1', 160, true),
  ('NITYA ENTERPRISES', 'full', 2, null, null, '2', 161, true),
  ('NORTHLAKHIMPUR- BAJAJ TRADING COMPANY', 'full', 1, null, null, '1', 162, true),
  ('NORTHLAKHIMPUR- L N  Enterprises', 'full', 1, null, null, '1', 163, true),
  ('PALI- VITTHAL HARI AGRO PROTEIN PVT LTD', 'full', 2, null, null, '2', 164, true),
  ('PANIPAT- GARG AGRO PRODUCTS LLP', 'full', 1, null, null, '1', 165, true),
  ('PANIPAT- MAA JAWALA OVERSEAS', 'full', 1, null, null, '1', 166, true),
  ('PANSARI INDUSTRIES', 'full', 4, null, null, '4', 167, true),
  ('PERFECT AGRO FOOD PVT LTD', 'full', 1, null, null, '1', 168, true),
  ('PUNJAB- A P ORGANICS LTD,', 'full', 2, null, null, '2', 169, true),
  ('PUNJAB- A P REFINERIES PVT LTD', 'full', null, null, null, null, 170, true),
  ('PUNJAB- A P REFINERY PVT LTD', 'full', 1, null, null, '1', 171, true),
  ('PUNJAB- GARG & COMPANY', 'full', 3, null, null, '3', 172, true),
  ('PUNJAB- GOYUM SCREW PRESS,', 'full', 4, null, null, '4', 173, true),
  ('PUNJAB- JPR SPPHIRE INDUSTRIES P LTD', 'full', 3, null, null, '3', 174, true),
  ('PUNJAB- SHREEJI  EXPELLER INDS', 'full', 1, null, null, '1', 175, true),
  ('R S INDUSTRIES PVT LTD (TIGER)', 'full', 12, null, null, '12', 176, true),
  ('RAJ BROKERS', 'full', 1, null, null, '1', 177, true),
  ('RAJASTHAN- ASSAM EDIBLE OIL P LTD TONK ( HELICOPTER)', 'full', 2, null, null, '2', 178, true),
  ('RAJASTHAN- BADAYA INDUSTRIES+AMRESHWAR', 'full', 1, null, null, '1', 179, true),
  ('RAJASTHAN- KASTURI INDIA (GANGANAGAR)', 'full', 2, null, null, '2', 180, true),
  ('RAJASTHAN- M J OIL INDUSTRIES,  PADAMPUR', 'full', 1, null, null, '1', 181, true),
  ('RAJASTHAN- PATANJALI FOODS LTD', 'full', 10, null, null, '10', 182, true),
  ('RAJASTHAN- SHIV EDIBLE (BAJRANG SABOO & GAGAN SABOO, KOTA', 'full', 2, null, null, '2', 183, true),
  ('RAJASTHAN- SHRI AMBRESHWAR FOOD PROD + BADAYA', 'full', 1, null, null, '1', 184, true),
  ('RAJHANS OIL MILLS PVT LTD || GST', 'full', 1, null, null, '1', 185, true),
  ('RAKESH SONI: EDC 09.09.26', 'full', 1, null, null, '1', 186, true),
  ('RAMNIWAS FLOUR MILLS :  RR GROUP LUCKNOW', 'full', null, null, null, null, 187, true),
  ('RAMSWRUPDASS GOKULCHAND', 'full', 1, null, null, '1', 188, true),
  ('RATHI OILS AND FOODS, MORENA', 'full', 2, null, null, '2', 189, true),
  ('RDG SOLVEX (VISHAL GARG) 9414187322 KOTA', 'full', 2, null, null, '2', 190, true),
  ('REGENT ENTERPRISES LTD', 'full', 1, null, null, '1', 191, true),
  ('S S OIL FIBRES', 'full', 1, null, null, '1', 192, true),
  ('SANMATI EDIBLE OILS PVT LTD', 'full', 1, null, null, '1', 193, true),
  ('SATPAL SONS : ANUJ AGARWAL+ HEMANT AGR SGU:9434021050', 'full', 2, null, null, '2', 194, true),
  ('SEHIRI INDUSTRIES', 'full', 2, null, null, '2', 195, true),
  ('SHARDA OIL INDUSTRIES PVT LTD', 'full', 1, null, null, '1', 196, true),
  ('SHILLONG- MEGHA OILS', 'full', 1, null, null, '1', 197, true),
  ('SHIVA FOODS', 'full', 1, null, null, '1', 198, true),
  ('SHIVAM OIL MILLS PVT LIMITYED', 'full', 1, null, null, '1', 199, true),
  ('SHIVANG EDIBLES OILS LIMITED', 'full', 2, null, null, '2', 200, true),
  ('SHREE GANESH EDIBLES P lTD (NEPA26-1034)', 'full', 1, null, null, '1', 201, true),
  ('SHREE GOBIND UDYOG PVT LTD', 'full', 2, null, null, '2', 202, true),
  ('SHREE HARI FOOD PROD PVT LTD (ENGINE) BHTR', 'full', 15, null, null, '15', 203, true),
  ('Shree Shankar Trading', 'full', null, null, null, null, 204, true),
  ('SHRI BHAGWAN SATISH KUMAR OIL GENERAL MILLS| GST', 'full', 1, null, null, '1', 205, true),
  ('SIBSAGAR- MAHABIR OIL INDUSTRIES : 9435057078', 'full', 2, null, null, '2', 206, true),
  ('SIBSAGAR- R K ENTERPRISE', 'full', null, null, null, null, 207, true),
  ('SIDHPUR- GOKUL AGRI INRL LIMITED', 'full', 5, null, null, '5', 208, true),
  ('SILCHAR- AGARWAL AGENCIES', 'full', 1, null, null, '1', 209, true),
  ('SILCHAR- ASHOKA TRADING COMPANY', 'full', 1, null, null, '1', 210, true),
  ('SILCHAR- B H ENTERPRISES', 'full', 1, null, null, '1', 211, true),
  ('SILCHAR- DUTTA BROS- SANKU DUTTA 16.09.26 EDC', 'full', 1, null, null, '1', 212, true),
  ('SILCHAR- H.M. STORE', 'full', 1, null, null, '1', 213, true),
  ('SILCHAR- HANUMAN PRASAD SHARMA', 'full', 1, null, null, '1', 214, true),
  ('SILCHAR- KALYAN AND SONS', 'full', null, null, null, null, 215, true),
  ('SILCHAR- Manoj Kumar Baid and Brothers', 'full', 2, null, null, '2', 216, true),
  ('SILCHAR- OSWAL TRADERS', 'full', 1, null, null, '1', 217, true),
  ('SILCHAR- PAWAN TRADERS', 'full', null, null, null, null, 218, true),
  ('SILCHAR- RATHI CORPORATION', 'full', 1, null, null, '1', 219, true),
  ('SILCHAR- SHREE JAGDAMBA ENTERPRISE', 'full', 1, null, null, '1', 220, true),
  ('SILCHAR- UNITED COMMERCIAL COMPANY', 'full', 1, null, null, '1', 221, true),
  ('SILIGURI- OSHO OIL', 'full', 1, null, null, '1', 222, true),
  ('SILIGURI- RIDHI SIDHI OIL INDS - 7865883156 PULKIT,', 'full', 1, null, null, '1', 223, true),
  ('SRESTH PRODUCTS PVT LTD||  SGT + ALLOCATION', 'full', 4, null, null, '4', 224, true),
  ('SUNANDA RAM DEKA , MANGALDOI', 'full', 1, null, null, '1', 225, true),
  ('SUNIL OIL BROKERS,', 'full', 1, null, null, '1', 226, true),
  ('TEZPUR- CHUNNILAL BOTHRA & SONS', 'full', 1, null, null, '1', 227, true),
  ('TEZPUR- GUNCHAND DALCHAND', 'full', 1, null, null, '1', 228, true),
  ('TEZPUR- JAISWAL TRADING', 'full', 1, null, null, '1', 229, true),
  ('TEZPUR- MOTILAL GYANCHAND', 'full', 1, null, null, '1', 230, true),
  ('TINSUKIA- INDIRA TRADING COMPANY,', 'full', 2, null, null, '2', 231, true),
  ('TINSUKIA- Govind Prasad Rajesh Kumar.', 'full', 1, null, null, '1', 232, true),
  ('TINSUKIA- GOPIRAM CHETRAM', 'full', 1, null, null, '1', 233, true),
  ('TINSUKIA- Krishna trading', 'full', 1, null, null, '1', 234, true),
  ('TINSUKIA- Mandhania Trading Co', 'full', 1, null, null, '1', 235, true),
  ('TINSUKIA- Tinsukia Trading Company Pvt. Ltd', 'full', 1, null, null, '1', 236, true),
  ('MARUTI NANDAN INDUSTRIES, (RAMESH JI AGARWAL)', 'full', 1, null, null, '1', 237, true),
  ('RELIANCE INDUSTRIES LTD, BANGALORE', 'full', 13, null, null, '13', 238, true),
  ('AMAN VYAPAR (PRESS)', 'free', 2, null, null, '2', 239, true),
  ('ANANT KR JAIN / MAHABIR TRADING COMPANY', 'free', null, null, null, null, 240, true),
  ('COOIT-DELHI  ( HOTEL ROOM FOC)', 'free', null, null, null, null, 241, true),
  ('DEVOTA', 'free', null, null, null, null, 242, true),
  ('I GRAIN INDIA (PRESS) *******', 'free', 2, null, null, '2', 243, true),
  ('JAIPUR MOPA             (HOTEL ROOM FOC)', 'free', null, null, null, null, 244, true),
  ('MIDHAS TOUCH  EVENT', 'free', null, null, null, null, 245, true),
  ('NEPA MANAGEMENT', 'free', null, null, null, null, 246, true),
  ('OIL & GRAIN ASIA (KOUSHIK)', 'free', 1, null, null, '1', 247, true),
  ('R K SINGHAL  (9810285269), DELHI', 'free', 2, null, null, '2', 248, true),
  ('RAJ  BROTHERS JAIPUR', 'free', null, null, null, null, 249, true),
  ('SHSHIL KAUSHIK (PRESS)', 'free', 2, null, null, '2', 250, true),
  ('SPEAKER', 'free', null, null, null, null, 251, true),
  ('SVR AGROTECH PVT LTD / MARUDHAR TRADING JPR', 'free', null, null, null, null, 252, true),
  ('ASHOKA OIL INDUSTRIES', 'action', null, null, null, null, 253, true),
  ('GOYAL FOODS', 'action', null, null, null, null, 254, true),
  ('GOYAL OIL MILLS', 'action', null, null, null, null, 255, true),
  ('SURJEET KUMAR', 'action', null, null, null, null, 256, true);

commit;

-- Verify:
select category, count(*) parties, sum(paid_count) delegates from parties group by category order by category;